Fix cppcheck
error: deallocuse - Dereferencing 'node_ptr' after
it is deallocated / released

Seems that:
NodeBaseInterface::WeakPtr node_weak_ptr(node_ptr);
causes the cppcheck to fail if node_ptr is used after creating
the weak pointer from it.