rclcpp_components: Fix compilation with clang (#3229)
This fixes the following error reported by clang:

    /ros/rclcpp/rclcpp_components/src/component_container.cpp:204:50: error: format string is not a string literal (potentially insecure) [-Werror,-Wformat-security]
      204 |   RCUTILS_LOG_DEBUG_NAMED("component_container", debug_msg.c_str());
          |                                                  ^~~~~~~~~~~~~~~~~
    /nix/store/2xvm1s7bkzj40vswqm9ihlfmq7bxb291-ros-env/include/rcutils/rcutils/logging_macros.h:352:55: note: expanded from macro 'RCUTILS_LOG_DEBUG_NAMED'
      352 |   RCUTILS_LOG_NAMED(RCUTILS_LOG_SEVERITY_DEBUG, name, __VA_ARGS__)
          |                                                       ^~~~~~~~~~~
    /nix/store/2xvm1s7bkzj40vswqm9ihlfmq7bxb291-ros-env/include/rcutils/rcutils/logging_macros.h:56:73: note: expanded from macro 'RCUTILS_LOG_NAMED'
       56 |       rcutils_log_internal(&__rcutils_logging_location, severity, name, __VA_ARGS__); \
          |                                                                         ^~~~~~~~~~~
    /home/wsh/src/ros/rclcpp/rclcpp_components/src/component_container.cpp:204:50: note: treat the string as an argument to avoid this
      204 |   RCUTILS_LOG_DEBUG_NAMED("component_container", debug_msg.c_str());
          |                                                  ^
          |                                                  "%s",
    /nix/store/2xvm1s7bkzj40vswqm9ihlfmq7bxb291-ros-env/include/rcutils/rcutils/logging_macros.h:352:55: note: expanded from macro 'RCUTILS_LOG_DEBUG_NAMED'
      352 |   RCUTILS_LOG_NAMED(RCUTILS_LOG_SEVERITY_DEBUG, name, __VA_ARGS__)
          |                                                       ^
    /nix/store/2xvm1s7bkzj40vswqm9ihlfmq7bxb291-ros-env/include/rcutils/rcutils/logging_macros.h:56:73: note: expanded from macro 'RCUTILS_LOG_NAMED'
       56 |       rcutils_log_internal(&__rcutils_logging_location, severity, name, __VA_ARGS__); \
          |                                                                         ^

Signed-off-by: Michal Sojka <michal.sojka@cvut.cz>
(cherry picked from commit 329abd884470b2693da0127604eb3cf1066c4112)